### ISSUE TITLE
Taking too long to load and then suddenly crashes

### ISSUE THREAD

**Issue by Hardy311t3** [Ramotion/garland-view-android#10]
Take so much time to load and then
Suddenly crashes with a dialog (Unfortunately, Application has stopped). And it happened 4/6 times I tried it on Samsumg Note 4 SM-N910F.

**Comment by dvg4000** [comment]
Can you provide error logs?

**Comment by pradeep2424** [comment]
```
> 02-09 12:28:26.776 27879-27879/? E/Zygote: MountEmulatedStorage()
> 02-09 12:28:26.776 27879-27879/? E/Zygote: v2
> 02-09 12:28:26.791 27879-27879/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
> 02-09 12:28:27.336 27879-27879/com.ramotion.garlandview.example E/RecyclerView: No adapter attached; skipping layout
> 02-09 12:28:27.341 27879-27879/com.ramotion.garlandview.example E/RecyclerView: No adapter attached; skipping layout
```

**Comment by ghost** [comment]
```
 02-09 12:28:26.776 27879-27879/? E/Zygote: MountEmulatedStorage()
> 02-09 12:28:26.776 27879-27879/? E/Zygote: v2
> 02-09 12:28:26.791 27879-27879/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
> 02-09 12:28:27.336 27879-27879/com.ramotion.garlandview.example E/RecyclerView: No adapter attached; skipping layout
> 02-09 12:28:27.341 27879-27879/com.ramotion.garlandview.example E/RecyclerView: No adapter attached; skipping layout
```

**Comment by HitRoxxx** [comment]
E/OpenGLRenderer: GL error:  GL_INVALID_VALUE
 A/OpenGLRenderer: GL errors! frameworks/base/libs/hwui/BakedOpRenderer.cpp:67
 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 24143 (RenderThread)        
                                                                       [ 02-12 23:59:43.683   397:  397 W/         ]
                                                                       debuggerd: handling request: pid=24009 uid=10128 gid=10128 tid=24143

**Comment by golovin47** [comment]
Hello, @HitRoxxx , @trayfullstackdevs , @Hardy311t3. Couldn't reproduce this issue in current version of this library. Try to update to the latest version. If this issue still there, please provide us with more specific description of how to reproduce it and complete error stacktrace. Until then this issue is considered closed.
