### ISSUE TITLE
Missing classes in library: `DataBindingUtil`

### ISSUE THREAD

**Issue by DevLucem** [Ramotion/garland-view-android#13]
https://github.com/Ramotion/garland-view-android/blob/6f8a3485577e7a178e94b4d84f3abee647359249/garland-view-example/src/main/java/com/ramotion/garlandview/example/main/inner/InnerAdapter.java#L21

This is a great library 👍 👍 👍 

I can't find the import of the following classes 
InnerItemBinding
ActivityDetailsBinding
ActivityProfileBinding
DetailsItemBinding

Is there a missing dependency? or omitted file?

**Comment by HitRoxxx** [comment]
Enable data binding in app build gradle 

dataBinding {
        enabled = true
    }

**Comment by firatcetiner** [comment]
How this issue closed? InnerItemBinding does not exist.

**Comment by golovin47** [comment]
If you've done what @HitRoxxx said and you have InnerItemBinding class in one of com folders in generatedJava folder, than you can import it manually to the place where this class is being used. Otherwise try rebuild your project or sync your gradle.

**Comment by firatcetiner** [comment]
Thank you!

**Comment by firatcetiner** [comment]
I did that already, but where is the implementation for InnerItemBinding?

**Comment by golovin47** [comment]
It should be generated automatically in folder: generatedJava->com (one of those)

**Comment by firatcetiner** [comment]
Okay. The problem is that it doesn't generate the class at all.

**Comment by golovin47** [comment]
Try to run garland-view-example. If it works properly, then this issue related to your implementation.

**Comment by firatcetiner** [comment]
I'll try that and share the result. Thanks a lot.

**Comment by firatcetiner** [comment]
The issue was related to my false/incomplete implementation.
