### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by PaolinoAngeletti** [Ramotion/garland-view-android#15]
![immagine](https://user-images.githubusercontent.com/24671034/52565908-72136300-2e08-11e9-9131-f3a2e93e1d4e.png)

**Comment by golovin47** [comment]
Hello, @PaolinoAngeletti. Right now garland-view-android uses the most recent versions of all tools and dependencies in build.gradle file. Issue, which this log shows looks like a clash of dependencies versions. Try updating all of your tools to the most recent ones in your project and app build.gradle files (look inside build.gradle file of garland-view-android [here](https://github.com/Ramotion/garland-view-android/blob/master/garland-view/build.gradle) and [here](https://github.com/Ramotion/garland-view-android/blob/master/build.gradle)). Also check how it is being used in garland-view-example app inside this repository with all dependencies and tools versions in build.gradle file.
