### ISSUE TITLE
no effect

### ISSUE THREAD

**Issue by tenSunFree** [Ramotion/garland-view-android#2]
![2017-09-15_120326](https://user-images.githubusercontent.com/23090085/30466161-56f358ee-9a0e-11e7-9ee3-3367d278abe1.jpg)

I would like to ask, the yellow box inside the code, it seems no effect?

**Comment by dvg4000** [comment]
It generates unique url for item's avatar. For example, if you change it to `faker.avatar.image()`, you will have same avatar for all items.

https://github.com/stympy/faker/blob/master/doc/avatar.md
