### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by tenSunFree** [Ramotion/garland-view-android#4]
![2017-09-17_090641](https://user-images.githubusercontent.com/23090085/30517121-b6badd36-9b87-11e7-9bd7-1dc9b0dbad4a.jpg)

I just opened the class, it suddenly appeared such an error message.

What is the reason for the error message?
What should I do?

**Comment by dvg4000** [comment]
It's `generated` class. There is no real error in this issue.

![image](https://user-images.githubusercontent.com/13576398/30594888-3da54684-9d58-11e7-9fdd-c198a0800196.png)
