### ISSUE TITLE
Scrolling bugged with only few inner items?

### ISSUE THREAD

**Issue by vb1508** [Ramotion/garland-view-android#8]
Hi,

I tried to use garland view in my project but I'm experiencing a pretty wierd issue. Whenever I have only one or two items in my InnerAdapter - such that they do not fill out the screen and I shouldn't be able to scroll - and when I eventually try to scroll, the InnerItems would just drop to the bottom and then disappear offscreen. I tried using the same code as from the example but had the same issue. Is it a bug or am I doing something wrong?

Thanks 
 
EDIT: I also tried to include a SearchView widget within the OuterItem, and every time I clear the search (e.g. pressing on "x") the adapter would automatically rotate to the previous outer item. Anyway to prevent this?

**Comment by dvg4000** [comment]
@vb1508 for the first issue, you'll need to wait for version update. 
For the second issue, you can try this workaround:

```java
public class Transformer extends com.ramotion.garlandview.header.HeaderTransformer {

    @Override
    public void transformPage(@NonNull HeaderItem item, float scrollPosition) {
        super.transformPage(item, scrollPosition);

        if (scrollPosition == -1f || scrollPosition == 1f) {
            ((ViewGroup)item.itemView).setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS);
        } else if (scrollPosition == 0) {
            ((ViewGroup)item.itemView).setDescendantFocusability(ViewGroup.FOCUS_AFTER_DESCENDANTS); // or ViewGroup.FOCUS_BEFORE_DESCENDANTS
        }
    }
}

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ...
        final TailRecyclerView rv = findViewById(R.id.recycler_view);
        final TailLayoutManager lm = (TailLayoutManager) rv.getLayoutManager();
        lm.setPageTransformer(new Transformer());
        ...
    }
    ...
}
```

**Comment by vb1508** [comment]
Hi,

I tried out the new version and everything is working fine. Is there a way to enable nested scrolling inside the header item (e.g. a horizontal recyclerview)?

**Comment by mejdi14** [comment]
Hi vb1508,
can you tell how did you manage to add a filter to this list.
