### ISSUE TITLE
Scrolling bugged with only one Outer Item

### ISSUE THREAD

**Issue by sangeetaggomes** [Ramotion/garland-view-android#9]
I tried to use garland view in my project  where I just wanted 1 outer item. Whenever I try to scroll the inner items with only 1 outer item, it stops scrolling vertically or it behaves weirdly. It works fine when scrolled very slowly but gives issue when scrolled fast.  Can you help me with this?

**Comment by dvg4000** [comment]
Did you try `0.3.2` version?

**Comment by sangeetaggomes** [comment]
Yes it is same with the 0.3.2 version.
I found the solution. Need to change 


    public boolean canScrollHorizontally() {
        return getChildCount() !=0;
    }
to

    public boolean canScrollHorizontally() {
        return getChildCount() >1;
    }

in TailLayoutManager class
